[master]
3.111.147.165 ansible_user=ec2-user ansible_ssh_private_key_file=/var/lib/jenkins/workspace/devops-cicd-pipeline/22nd-Sep.pem

[workers]
3.110.161.207 ansible_user=ec2-user ansible_ssh_private_key_file=/var/lib/jenkins/workspace/devops-cicd-pipeline/22nd-Sep.pem

[k8s_cluster:children]
master
workers

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3
