[k8s_master]
3.111.32.154 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/22nd-Sep.pem

[k8s_workers]
13.232.255.82 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/22nd-Sep.pem

[all:vars]
ansible_python_interpreter=/usr/bin/python3
